// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: editor_proto_files/PlayBoardEdit.proto

#include "editor_proto_files/PlayBoardEdit.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Arkanoids3d {
PROTOBUF_CONSTEXPR Point::Point(
    ::_pbi::ConstantInitialized)
  : x_(0)
  , y_(0)
  , z_(0){}
struct PointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PointDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PointDefaultTypeInternal() {}
  union {
    Point _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PointDefaultTypeInternal _Point_default_instance_;
PROTOBUF_CONSTEXPR EditBlockResult::EditBlockResult(
    ::_pbi::ConstantInitialized)
  : errormessage_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , result_(0)

  , blockcode_(0){}
struct EditBlockResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EditBlockResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EditBlockResultDefaultTypeInternal() {}
  union {
    EditBlockResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EditBlockResultDefaultTypeInternal _EditBlockResult_default_instance_;
PROTOBUF_CONSTEXPR SetBoardDescriptionResult::SetBoardDescriptionResult(
    ::_pbi::ConstantInitialized)
  : result_(0)
{}
struct SetBoardDescriptionResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetBoardDescriptionResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetBoardDescriptionResultDefaultTypeInternal() {}
  union {
    SetBoardDescriptionResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetBoardDescriptionResultDefaultTypeInternal _SetBoardDescriptionResult_default_instance_;
PROTOBUF_CONSTEXPR void_::void_(
    ::_pbi::ConstantInitialized){}
struct void_DefaultTypeInternal {
  PROTOBUF_CONSTEXPR void_DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~void_DefaultTypeInternal() {}
  union {
    void_ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 void_DefaultTypeInternal _void__default_instance_;
PROTOBUF_CONSTEXPR BoardDescription::BoardDescription(
    ::_pbi::ConstantInitialized)
  : data_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , width_(0)
  , height_(0)
  , depth_(0){}
struct BoardDescriptionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BoardDescriptionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BoardDescriptionDefaultTypeInternal() {}
  union {
    BoardDescription _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BoardDescriptionDefaultTypeInternal _BoardDescription_default_instance_;
}  // namespace Arkanoids3d
static ::_pb::Metadata file_level_metadata_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto = nullptr;

const uint32_t TableStruct_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::Point, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::Point, x_),
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::Point, y_),
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::Point, z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::EditBlockResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::EditBlockResult, result_),
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::EditBlockResult, blockcode_),
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::EditBlockResult, errormessage_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::SetBoardDescriptionResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::SetBoardDescriptionResult, result_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::void_, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::BoardDescription, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::BoardDescription, width_),
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::BoardDescription, height_),
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::BoardDescription, depth_),
  PROTOBUF_FIELD_OFFSET(::Arkanoids3d::BoardDescription, data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Arkanoids3d::Point)},
  { 9, -1, -1, sizeof(::Arkanoids3d::EditBlockResult)},
  { 18, -1, -1, sizeof(::Arkanoids3d::SetBoardDescriptionResult)},
  { 25, -1, -1, sizeof(::Arkanoids3d::void_)},
  { 31, -1, -1, sizeof(::Arkanoids3d::BoardDescription)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Arkanoids3d::_Point_default_instance_._instance,
  &::Arkanoids3d::_EditBlockResult_default_instance_._instance,
  &::Arkanoids3d::_SetBoardDescriptionResult_default_instance_._instance,
  &::Arkanoids3d::_void__default_instance_._instance,
  &::Arkanoids3d::_BoardDescription_default_instance_._instance,
};

const char descriptor_table_protodef_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n&editor_proto_files/PlayBoardEdit.proto"
  "\022\013Arkanoids3d\"(\n\005Point\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002"
  " \001(\005\022\t\n\001z\030\003 \001(\005\"\322\001\n\017EditBlockResult\0223\n\006r"
  "esult\030\001 \001(\0162#.Arkanoids3d.EditBlockResul"
  "t.Result\022\021\n\tblockCode\030\002 \001(\005\022\024\n\014errorMess"
  "age\030\003 \001(\t\"a\n\006Result\022\017\n\013SPACE_EMPTY\020\000\022\022\n\016"
  "BLOCK_AT_SPACE\020\001\022\037\n\033FAILURE_POINT_OUT_OF"
  "_BOUNDS\020\002\022\021\n\rOTHER_FAILURE\020\003\"\270\001\n\031SetBoar"
  "dDescriptionResult\022=\n\006result\030\001 \001(\0162-.Ark"
  "anoids3d.SetBoardDescriptionResult.Resul"
  "t\"\\\n\006Result\022\013\n\007SUCCESS\020\000\022\"\n\036FAILURE_TOO_"
  "MANY_BYTES_FOR_WHD\020\001\022!\n\035FAILURE_TOO_FEW_"
  "BYTES_FOR_WHD\020\002\"\006\n\004void\"N\n\020BoardDescript"
  "ion\022\r\n\005width\030\001 \001(\005\022\016\n\006height\030\002 \001(\005\022\r\n\005de"
  "pth\030\003 \001(\005\022\014\n\004data\030\004 \001(\0142\251\002\n\rPlayBoardEdi"
  "t\022<\n\010AddBlock\022\022.Arkanoids3d.Point\032\034.Arka"
  "noids3d.EditBlockResult\022\?\n\013RemoveBlock\022\022"
  ".Arkanoids3d.Point\032\034.Arkanoids3d.EditBlo"
  "ckResult\022A\n\rGetBoardState\022\021.Arkanoids3d."
  "void\032\035.Arkanoids3d.BoardDescription\022V\n\rS"
  "etBoardState\022\035.Arkanoids3d.BoardDescript"
  "ion\032&.Arkanoids3d.SetBoardDescriptionRes"
  "ultb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto = {
    false, false, 891, descriptor_table_protodef_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto,
    "editor_proto_files/PlayBoardEdit.proto",
    &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto::offsets,
    file_level_metadata_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto, file_level_enum_descriptors_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto,
    file_level_service_descriptors_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_getter() {
  return &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto(&descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto);
namespace Arkanoids3d {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EditBlockResult_Result_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto);
  return file_level_enum_descriptors_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[0];
}
bool EditBlockResult_Result_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr EditBlockResult_Result EditBlockResult::SPACE_EMPTY;
constexpr EditBlockResult_Result EditBlockResult::BLOCK_AT_SPACE;
constexpr EditBlockResult_Result EditBlockResult::FAILURE_POINT_OUT_OF_BOUNDS;
constexpr EditBlockResult_Result EditBlockResult::OTHER_FAILURE;
constexpr EditBlockResult_Result EditBlockResult::Result_MIN;
constexpr EditBlockResult_Result EditBlockResult::Result_MAX;
constexpr int EditBlockResult::Result_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SetBoardDescriptionResult_Result_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto);
  return file_level_enum_descriptors_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[1];
}
bool SetBoardDescriptionResult_Result_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr SetBoardDescriptionResult_Result SetBoardDescriptionResult::SUCCESS;
constexpr SetBoardDescriptionResult_Result SetBoardDescriptionResult::FAILURE_TOO_MANY_BYTES_FOR_WHD;
constexpr SetBoardDescriptionResult_Result SetBoardDescriptionResult::FAILURE_TOO_FEW_BYTES_FOR_WHD;
constexpr SetBoardDescriptionResult_Result SetBoardDescriptionResult::Result_MIN;
constexpr SetBoardDescriptionResult_Result SetBoardDescriptionResult::Result_MAX;
constexpr int SetBoardDescriptionResult::Result_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Point::_Internal {
 public:
};

Point::Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:Arkanoids3d.Point)
}
Point::Point(const Point& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:Arkanoids3d.Point)
}

inline void Point::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&x_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
}

Point::~Point() {
  // @@protoc_insertion_point(destructor:Arkanoids3d.Point)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Point::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Point::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Point::Clear() {
// @@protoc_insertion_point(message_clear_start:Arkanoids3d.Point)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Point::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          y_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          z_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Point::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arkanoids3d.Point)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->_internal_x() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_x(), target);
  }

  // int32 y = 2;
  if (this->_internal_y() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_y(), target);
  }

  // int32 z = 3;
  if (this->_internal_z() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arkanoids3d.Point)
  return target;
}

size_t Point::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arkanoids3d.Point)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->_internal_x() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_x());
  }

  // int32 y = 2;
  if (this->_internal_y() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_y());
  }

  // int32 z = 3;
  if (this->_internal_z() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_z());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Point::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Point::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Point::GetClassData() const { return &_class_data_; }

void Point::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Point *>(to)->MergeFrom(
      static_cast<const Point &>(from));
}


void Point::MergeFrom(const Point& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arkanoids3d.Point)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_x() != 0) {
    _internal_set_x(from._internal_x());
  }
  if (from._internal_y() != 0) {
    _internal_set_y(from._internal_y());
  }
  if (from._internal_z() != 0) {
    _internal_set_z(from._internal_z());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Point::CopyFrom(const Point& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arkanoids3d.Point)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Point::IsInitialized() const {
  return true;
}

void Point::InternalSwap(Point* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Point, z_)
      + sizeof(Point::z_)
      - PROTOBUF_FIELD_OFFSET(Point, x_)>(
          reinterpret_cast<char*>(&x_),
          reinterpret_cast<char*>(&other->x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Point::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_getter, &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_once,
      file_level_metadata_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[0]);
}

// ===================================================================

class EditBlockResult::_Internal {
 public:
};

EditBlockResult::EditBlockResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:Arkanoids3d.EditBlockResult)
}
EditBlockResult::EditBlockResult(const EditBlockResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  errormessage_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    errormessage_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_errormessage().empty()) {
    errormessage_.Set(from._internal_errormessage(), 
      GetArenaForAllocation());
  }
  ::memcpy(&result_, &from.result_,
    static_cast<size_t>(reinterpret_cast<char*>(&blockcode_) -
    reinterpret_cast<char*>(&result_)) + sizeof(blockcode_));
  // @@protoc_insertion_point(copy_constructor:Arkanoids3d.EditBlockResult)
}

inline void EditBlockResult::SharedCtor() {
errormessage_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  errormessage_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&result_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&blockcode_) -
    reinterpret_cast<char*>(&result_)) + sizeof(blockcode_));
}

EditBlockResult::~EditBlockResult() {
  // @@protoc_insertion_point(destructor:Arkanoids3d.EditBlockResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EditBlockResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  errormessage_.Destroy();
}

void EditBlockResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void EditBlockResult::Clear() {
// @@protoc_insertion_point(message_clear_start:Arkanoids3d.EditBlockResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  errormessage_.ClearToEmpty();
  ::memset(&result_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&blockcode_) -
      reinterpret_cast<char*>(&result_)) + sizeof(blockcode_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EditBlockResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Arkanoids3d.EditBlockResult.Result result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result(static_cast<::Arkanoids3d::EditBlockResult_Result>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 blockCode = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          blockcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string errorMessage = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_errormessage();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Arkanoids3d.EditBlockResult.errorMessage"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EditBlockResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arkanoids3d.EditBlockResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Arkanoids3d.EditBlockResult.Result result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_result(), target);
  }

  // int32 blockCode = 2;
  if (this->_internal_blockcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_blockcode(), target);
  }

  // string errorMessage = 3;
  if (!this->_internal_errormessage().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_errormessage().data(), static_cast<int>(this->_internal_errormessage().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Arkanoids3d.EditBlockResult.errorMessage");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_errormessage(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arkanoids3d.EditBlockResult)
  return target;
}

size_t EditBlockResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arkanoids3d.EditBlockResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string errorMessage = 3;
  if (!this->_internal_errormessage().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_errormessage());
  }

  // .Arkanoids3d.EditBlockResult.Result result = 1;
  if (this->_internal_result() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result());
  }

  // int32 blockCode = 2;
  if (this->_internal_blockcode() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_blockcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EditBlockResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    EditBlockResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EditBlockResult::GetClassData() const { return &_class_data_; }

void EditBlockResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<EditBlockResult *>(to)->MergeFrom(
      static_cast<const EditBlockResult &>(from));
}


void EditBlockResult::MergeFrom(const EditBlockResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arkanoids3d.EditBlockResult)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_errormessage().empty()) {
    _internal_set_errormessage(from._internal_errormessage());
  }
  if (from._internal_result() != 0) {
    _internal_set_result(from._internal_result());
  }
  if (from._internal_blockcode() != 0) {
    _internal_set_blockcode(from._internal_blockcode());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EditBlockResult::CopyFrom(const EditBlockResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arkanoids3d.EditBlockResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EditBlockResult::IsInitialized() const {
  return true;
}

void EditBlockResult::InternalSwap(EditBlockResult* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &errormessage_, lhs_arena,
      &other->errormessage_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EditBlockResult, blockcode_)
      + sizeof(EditBlockResult::blockcode_)
      - PROTOBUF_FIELD_OFFSET(EditBlockResult, result_)>(
          reinterpret_cast<char*>(&result_),
          reinterpret_cast<char*>(&other->result_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EditBlockResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_getter, &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_once,
      file_level_metadata_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[1]);
}

// ===================================================================

class SetBoardDescriptionResult::_Internal {
 public:
};

SetBoardDescriptionResult::SetBoardDescriptionResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:Arkanoids3d.SetBoardDescriptionResult)
}
SetBoardDescriptionResult::SetBoardDescriptionResult(const SetBoardDescriptionResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:Arkanoids3d.SetBoardDescriptionResult)
}

inline void SetBoardDescriptionResult::SharedCtor() {
result_ = 0;
}

SetBoardDescriptionResult::~SetBoardDescriptionResult() {
  // @@protoc_insertion_point(destructor:Arkanoids3d.SetBoardDescriptionResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SetBoardDescriptionResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SetBoardDescriptionResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SetBoardDescriptionResult::Clear() {
// @@protoc_insertion_point(message_clear_start:Arkanoids3d.SetBoardDescriptionResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  result_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetBoardDescriptionResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Arkanoids3d.SetBoardDescriptionResult.Result result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result(static_cast<::Arkanoids3d::SetBoardDescriptionResult_Result>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetBoardDescriptionResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arkanoids3d.SetBoardDescriptionResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Arkanoids3d.SetBoardDescriptionResult.Result result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arkanoids3d.SetBoardDescriptionResult)
  return target;
}

size_t SetBoardDescriptionResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arkanoids3d.SetBoardDescriptionResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Arkanoids3d.SetBoardDescriptionResult.Result result = 1;
  if (this->_internal_result() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetBoardDescriptionResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SetBoardDescriptionResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetBoardDescriptionResult::GetClassData() const { return &_class_data_; }

void SetBoardDescriptionResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SetBoardDescriptionResult *>(to)->MergeFrom(
      static_cast<const SetBoardDescriptionResult &>(from));
}


void SetBoardDescriptionResult::MergeFrom(const SetBoardDescriptionResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arkanoids3d.SetBoardDescriptionResult)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _internal_set_result(from._internal_result());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetBoardDescriptionResult::CopyFrom(const SetBoardDescriptionResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arkanoids3d.SetBoardDescriptionResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetBoardDescriptionResult::IsInitialized() const {
  return true;
}

void SetBoardDescriptionResult::InternalSwap(SetBoardDescriptionResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(result_, other->result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SetBoardDescriptionResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_getter, &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_once,
      file_level_metadata_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[2]);
}

// ===================================================================

class void_::_Internal {
 public:
};

void_::void_(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Arkanoids3d.void)
}
void_::void_(const void_& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Arkanoids3d.void)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData void_::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*void_::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata void_::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_getter, &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_once,
      file_level_metadata_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[3]);
}

// ===================================================================

class BoardDescription::_Internal {
 public:
};

BoardDescription::BoardDescription(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:Arkanoids3d.BoardDescription)
}
BoardDescription::BoardDescription(const BoardDescription& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    data_.Set(from._internal_data(), 
      GetArenaForAllocation());
  }
  ::memcpy(&width_, &from.width_,
    static_cast<size_t>(reinterpret_cast<char*>(&depth_) -
    reinterpret_cast<char*>(&width_)) + sizeof(depth_));
  // @@protoc_insertion_point(copy_constructor:Arkanoids3d.BoardDescription)
}

inline void BoardDescription::SharedCtor() {
data_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  data_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&width_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&depth_) -
    reinterpret_cast<char*>(&width_)) + sizeof(depth_));
}

BoardDescription::~BoardDescription() {
  // @@protoc_insertion_point(destructor:Arkanoids3d.BoardDescription)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BoardDescription::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  data_.Destroy();
}

void BoardDescription::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BoardDescription::Clear() {
// @@protoc_insertion_point(message_clear_start:Arkanoids3d.BoardDescription)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmpty();
  ::memset(&width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&depth_) -
      reinterpret_cast<char*>(&width_)) + sizeof(depth_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BoardDescription::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 width = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 height = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 depth = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          depth_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BoardDescription::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arkanoids3d.BoardDescription)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 width = 1;
  if (this->_internal_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_width(), target);
  }

  // int32 height = 2;
  if (this->_internal_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_height(), target);
  }

  // int32 depth = 3;
  if (this->_internal_depth() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_depth(), target);
  }

  // bytes data = 4;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arkanoids3d.BoardDescription)
  return target;
}

size_t BoardDescription::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arkanoids3d.BoardDescription)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 4;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // int32 width = 1;
  if (this->_internal_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_width());
  }

  // int32 height = 2;
  if (this->_internal_height() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_height());
  }

  // int32 depth = 3;
  if (this->_internal_depth() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_depth());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BoardDescription::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BoardDescription::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BoardDescription::GetClassData() const { return &_class_data_; }

void BoardDescription::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BoardDescription *>(to)->MergeFrom(
      static_cast<const BoardDescription &>(from));
}


void BoardDescription::MergeFrom(const BoardDescription& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arkanoids3d.BoardDescription)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _internal_set_data(from._internal_data());
  }
  if (from._internal_width() != 0) {
    _internal_set_width(from._internal_width());
  }
  if (from._internal_height() != 0) {
    _internal_set_height(from._internal_height());
  }
  if (from._internal_depth() != 0) {
    _internal_set_depth(from._internal_depth());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BoardDescription::CopyFrom(const BoardDescription& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arkanoids3d.BoardDescription)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoardDescription::IsInitialized() const {
  return true;
}

void BoardDescription::InternalSwap(BoardDescription* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &data_, lhs_arena,
      &other->data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BoardDescription, depth_)
      + sizeof(BoardDescription::depth_)
      - PROTOBUF_FIELD_OFFSET(BoardDescription, width_)>(
          reinterpret_cast<char*>(&width_),
          reinterpret_cast<char*>(&other->width_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BoardDescription::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_getter, &descriptor_table_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto_once,
      file_level_metadata_editor_5fproto_5ffiles_2fPlayBoardEdit_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Arkanoids3d
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Arkanoids3d::Point*
Arena::CreateMaybeMessage< ::Arkanoids3d::Point >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arkanoids3d::Point >(arena);
}
template<> PROTOBUF_NOINLINE ::Arkanoids3d::EditBlockResult*
Arena::CreateMaybeMessage< ::Arkanoids3d::EditBlockResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arkanoids3d::EditBlockResult >(arena);
}
template<> PROTOBUF_NOINLINE ::Arkanoids3d::SetBoardDescriptionResult*
Arena::CreateMaybeMessage< ::Arkanoids3d::SetBoardDescriptionResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arkanoids3d::SetBoardDescriptionResult >(arena);
}
template<> PROTOBUF_NOINLINE ::Arkanoids3d::void_*
Arena::CreateMaybeMessage< ::Arkanoids3d::void_ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arkanoids3d::void_ >(arena);
}
template<> PROTOBUF_NOINLINE ::Arkanoids3d::BoardDescription*
Arena::CreateMaybeMessage< ::Arkanoids3d::BoardDescription >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arkanoids3d::BoardDescription >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
